spring:
  application:
    name: spring-kafka-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "payment-group-id"
    properties:
      schema.registry.url: http://localhost:8081